### ISSUE TITLE
Questions about the Domainnet data list

### ISSUE THREAD

**Issue by qiuzhen8484** [Codeontheway/ISFDA-master#1]
Although highlight in the paper that "we make no extra modification for Domainnet", why are the data txts for Domainnet much smaller than original dataset?

Thanks!

**Comment by LeoXinhaoLee** [comment]
Hi, thanks for your interest in our work. This is because in our paper we used a subset of the original DomainNet dataset that is created by the authors of the paper "Class-imbalanced Domain Adaptation: An Empirical Odyssey", as explained in the section for dataset information in our paper. Since this subset is naturally class-imbalanced, we made no extra modification to its label distribution. For more details regarding this dataset, please check out the above-mentioned paper by Tan et al.
